
services:
  backend:
    build:
      context: .
      dockerfile: ./src/backend_v2/Dockerfile
    ports:
      - "5172:5172"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://auditor_v2:auditor123%21@host.docker.internal:5432/audit_v2
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    working_dir: /app

  frontend:
    env_file:
      - .env
    environment:
      - VITE_API_BASE_URL=http://localhost:5172
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: audit-frontend
    ports:
      - "5173:5173"